on:
  push:
    branches:
    - main

permissions:
  contents: read

name: Main
jobs:
  build:
    name: Build (${{matrix.architecture}}, ${{matrix.configuration}})
    runs-on: windows-2025-vs2026

    strategy:
      fail-fast: false
      matrix:
        architecture: [ x86, x64, arm64 ]
        configuration: [ Debug, Release ]

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 #v6.0.3
        with:
          persist-credentials: false

      - name: Build configure
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\18\Enterprise\Common7\Tools\VsDevCmd.bat"
          msbuild Configure.sln /m /t:Rebuild /p:Configuration=${{matrix.configuration}},Platform=${{matrix.architecture}}
